### ISSUE TITLE
Move from boltdb to LevelDB

### ISSUE THREAD

**Issue by akrennmair** [akrennmair/cabinet#3]
Migrate the storage-related part from boltdb to LevelDB.

**Comment by abourget** [comment]
I'm curious, why the move to leveldb ?

**Comment by akrennmair** [comment]
Just look at benchmarks of the different key-value stores for Go. boltdb is quite a bit behind its contenders. That was also my experience in this project: while conceptually nice, it didn't perform well enough compared to LevelDB.

**Comment by abourget** [comment]
Interesting. Do you have any links? I'd like to see..

**Comment by akrennmair** [comment]
https://github.com/SchumacherFM/gokvbench/blob/master/README.md for example.
